# This file is generated by the Ntupling Service backend 

import os, yaml 
from pathlib import Path 
import sys 

AnalysisHelpers_Path = Path(os.environ['DAVINCI_PROJECT_ROOT']) / 'Phys' / 'AnalysisHelpers' / 'options' 
sys.path.append(str(AnalysisHelpers_Path)) 
from decaytreetuple import configure_dtt 
from Configurables import DaVinci 

config_file = Path(os.environ['ANALYSIS_PRODUCTIONS_BASE']) / "OmegaCOpenDataTest" / "DecayTree.yaml"
config = yaml.safe_load(open(config_file, 'rb')) 
dtt = configure_dtt(config) 
DaVinci().UserAlgorithms += [dtt] 

from PhysConf.Filters import LoKi_Filters 
fltrs = LoKi_Filters ( 
    STRIP_Code = "HLT_PASS_RE('StrippingOmegaCstarForPromptCharmDecision')" 
) 
DaVinci().EventPreFilters = fltrs.filters('Filters') 
